language: node_js
node_js:
- node
deploy:
  provider: heroku
  app: computer-vision
  api_key: 
    secure: lm4zZdG1AvHRGpqohYO732ILQr8AynNvGH3QEuprdwKbeyGgua46aLdwr9MfEuBXVojYpmb9LXr3Dtk/Wv5kI9F105lf/gOFjClnVpwgfunK4EBuhRVz3OV+VTkr6+bOInmRF26VydklZIBDDrrRNl4W2V0ZLBflXxM1JFhpQ6RwCz1JOORjQ7UhelnZ780DPGc0cKe2ceVfk90u0ZBOUN+kCZ1ycz+/8/b9PR0PFv7340YSbwQJJKmBcGEbe/qXLMGZxv0d0tmow5NTYiLe4bupvc2upr0X511ECZ4lAwkLoWVkS1sxjR/7Q1v/y3MuCwrI4/F9r2PvDEmVlKItFdtkFh2MjTCSbKyRhV3Rhx7S01f1ddc7i5q1rCHhe1tEivy7fsIRCZAMRMqMbvInPcdxDBGRh9rPZuTUzzLqL42pNjez7ZalP/EA5QXbmdBKirTRcTJ/VqoLj1QiCsK913MiFRcj3w0zk1DjZQn9tOQuCfqpyLo9dFl1NTG3eOKXDy5Top07JumlMtBczyB0MOrvn7r/e8xru6NrMUDvjzyoVaQr6TpZwVJRbdzNHoXlEWKh/FCPQ6mVblqSOJDvqT52+aRlzgp2gicLg1TFRTdwPtQDiVvsPrFXn8RTR3qbPGJKh8QTXrmrPPAfYn7K4vMFWj6DfnqySfokpIM07zs=
